spring:
  application:
    name: cart-web
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#购物车
CART_COOKIE_KEY: CART_COOKIE_KEY
CART_COOKIE_EXPIRE: 604800
# 设置feign的超时
#请求连接的超时时间
ribbon:
  ConnectTimeout: 60000
  #请求处理的超时时间
  ReadTimeout: 60000