spring:
  application:
    name: sso-web
server:
  port: 8777
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

# 设置feign的超时
#请求连接的超时时间
ribbon:
  ConnectTimeout: 60000
  #请求处理的超时时间
  ReadTimeout: 60000