server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8
    username: root
    password: mysqlroot
    type: com.alibaba.druid.pool.DruidDataSource
#订单
ORDER_ID_KEY: ORDER_ID_KEY
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY